import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    horizontalSection:{
      flexDirection:'row',
      alignItems:'center',
    },
    roundedTab:{
        borderWidth:1,
        borderColor:'#E4E8EE',
        borderRadius:20,
        paddingVertical:8,
        paddingHorizontal:12,
        backgroundColor:"#ffffff",
        marginHorizontal:4,
        flexDirection:'row',
        alignItems:'center'
    },
    roundedTabCustom:{
        borderWidth:1,
        borderColor:'#E4E8EE',
        borderRadius:50,
        paddingVertical:8,
        paddingHorizontal:10,
        backgroundColor:"#ffffff",
        marginHorizontal:4,
        flexDirection:'row',
        alignItems:'center',
        minWidth:100
    },
    tabText:{
        fontSize:14,
        fontFamily:'Poppins-Medium',
        color:"#02111A",
        textAlign:'center'
    },
    selectedRoundedTab:{
        borderWidth:1,
        borderColor:'#ffffff',
        borderRadius:20,
        paddingVertical:8,
        paddingHorizontal:12,
        backgroundColor:"#B10606",
        marginHorizontal:4,
        flexDirection:'row',
        alignItems:'center'
    },
    selectedRoundedTabCustom:{
        borderWidth:1,
        borderColor:'#ffffff',
        borderRadius:50,
        paddingVertical:8,
        paddingHorizontal:10,
        backgroundColor:"#ed714d",
        marginHorizontal:4,
        flexDirection:'row',
        alignItems:'center',
        minWidth:100
    },
    selectedTabText:{
        fontSize:14,
        fontFamily:'Poppins-Medium',
        color:"#ffffff",
        textAlign:'center'
    },
    icon:{
        width:10,
        height:10,
        marginLeft:4,
    },
    selImageBox:{
        backgroundColor:'white',
        borderRadius:50,
        marginRight:5,
        padding:6
    },
    imageBox:{
        backgroundColor:'#FEF5F3',
        borderRadius:50,
        marginRight:5,
        padding:6
    },
    CustomIcon:{
        width:20,
        height:20,
        borderRadius:50,
    }
})